import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/nav/Navbar';
import Providers from './Providers';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="dark">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background px-60 flex flex-col max-h-screen overflow-hidden`}
         >
            <Navbar />
            <main className="flex-grow">
               <Providers>{children}</Providers>
            </main>
         </body>
      </html>
   );
}
